keyResidues:
  Ser249:
    CHAIN_ID: "A"
    RES_ID: "249"
    RES_NAME: "SER"

analysisMenu:
  keyResidueAnalysis:
    contactDistances: False
    radialDistribution: False
    findHydrogenBonds: True
  wholeProteinAnalysis:
    RMSD: False
    RMSF: False
    deltaRMSF: False
    radiusOfGyration: False
  referenceSystem: False

  
pathInfo:
  mdDir: "/home/esp/scriptDevelopment/drMD/03_outputs"
  analDir: "/home/esp/scriptDevelopment/drMD/Analysis"
  stepName: "05_NpT_production_MD"
  repeats:
    solo_383187:
    - "383187_A"
