keyResidues:
  Glu3A:
    CHAIN_ID: "A"
    RES_ID: "3"
    RES_NAME: "GLU"
  Arg7B:
    CHAIN_ID: "B"
    RES_ID: "7"
    RES_NAME: "ARG" 

analysisMenu:
  keyResidueAnalysis:
    contactDistances: True
    radialDistribution: False
    findHydrogenBonds: True
  wholeProteinAnalysis:
    RMSD: False
    RMSF: False
    deltaRMSF: False
    radiusOfGyration: False
  referenceSystem: False

  
pathInfo:
  mdDir: "/home/esp/scriptDevelopment/drMD/03_outputs"
  analDir: "/home/esp/scriptDevelopment/drMD/Analysis"
  stepName: "05_NpT_equilibriation"
  repeats:
    5pth:
    - "5pth_A"
    - "5pth_B"
    Round2:
    - "5pth_A"
    - "5pth_B"
