########################################################################
pathInfo:
  inputDir: "/home/esp/scriptDevelopment/drMD/00_inputs"
  outputDir: "/home/esp/scriptDevelopment/drMD/01_outputs"
########################################################################
simulationInfo:
  - stepName: "01_energy_minimisation"
    type: "EM"
    temp: 300
    gpu: True
########################################################################
cleanUpInfo:
  pdbOnly: True