########################################################################
pathInfo:
  inputDir: "full/path/to/drMD/00_inputs"
  outputDir: "full/path/to/drMD/01_outputs"
########################################################################
simulationInfo:
  - stepName: "01_energy_minimisation"
    type: "EM"
    temp: 300
    gpu: True
########################################################################
cleanUpInfo:
  pdbOnly: True