########################################################################
pathInfo:
  inputDir: "/home/esp/scriptDevelopment/drMD/00_inputs"
  inputPdb: "/home/esp/scriptDevelopment/drMD/00_inputs/cvFAP_WT_PLM_FAD.pdb"
  outputDir: "/home/esp/scriptDevelopment/drMD/01_outputs"
  outputName: "cvFAP_FAD_PLM"
########################################################################
proteinInfo:
  nProteins: 1
  proteins:
    - proteinName: "cvFAP_WT"
      protons: False
########################################################################
ligandInfo:
  nLigands: 2
  ligands:
    - ligandName: "PLM"
      protons: False
      charge: -1
      toppar: False
      mol2: False
    - ligandName: "FAD"
      protons: False
      charge: -2
      toppar: False
      mol2: False
########################################################################
simulationInfo:
  - stepName: "01_energy_minimisation"
    type: "EM"
    temp: 300

  - stepName: "02_NVT_pre-equilibraition"
    type: "NVT"
    duration: "100 ps"
    timestep: "2 fs"
    freezeHeavy: True
    temp: 300

  - stepName: "03_NpT_pre-equilibriation"
    type: "NpT"
    duration: "100 ps"
    timestep: "2 fs"
    freezeHeavy: True
    temp: 300

  - stepName: "04_NpT_equilibriation"
    type: "NpT"
    duration: "10 ns"
    timestep: "2 fs"
    freezeHeavy: False
    temp: 300

  - stepName: "05_NpT_production MD"
    type: "NpT"
    duration: "50 ns"
    timestep: "2 fs"
    freezeHeavy: False
    temp: 300

########################################################################