########################################################################
pathInfo:
  inputDir: "/home/eugene/drMD/01_inputs"
  outputDir: "/scratch/cvFAP_MD"
########################################################################
generalInfo:
  cpuCount: 9
########################################################################
ligandInfo:
  nLigands: 2
  ligands:
    - ligandName: "PLM"
      protons: False
      charge: -1
      toppar: True
      mol2: True
    - ligandName: "FAD"
      protons: True
      charge: -2
      toppar: False
      mol2: False
########################################################################
simulationInfo:
  - stepName: "1_energy_minimisation"
    type: "EM"
    temp: 300
    maxIterations: 1000

  - stepName: "2_NVT_pre-equilibraition"
    type: "NVT"
    duration: "100 ps"
    timestep: "2 fs"
    relaxWaters: True
    temp: 300

  - stepName: "3_NpT_pre-equilibriation"
    type: "NpT"
    duration: "300 ps"
    timestep: "2 fs"
    relaxWaters: True
    temp: 300

  - stepName: "4_NpT_slowIntergrator"
    type: "NpT"
    duration: "10 ps"
    timestep: "0.5 fs"
    temp: 300

  - stepName: "5_NpT_equilibriation"
    type: "NpT"
    duration: "1 ns"
    timestep: "2 fs"
    temp: 300

  - stepName: "6_NpT_production"
    type: "NpT"
    duration: "50 ns"
    timestep: "2 fs"
    freezeHeavy: False
    temp: 300

########################################################################
cleanUpInfo:
  getEndpointPdbs: True
  removeWaters : True
  removeIons : True
  keepFileNames: True