########################################################################
pathInfo:
  inputDir: "/home/esp/scriptDevelopment/drMD/01_inputs"
  outputDir: "/home/esp/scriptDevelopment/drMD/03_outputs"
  
########################################################################
generalInfo:
  parallelCPU: 1
  platform: "CUDA"
  subprocessCpus: 1

########################################################################
ligandInfo:
  nLigands: 1
  ligands:
    - ligandName: "FMN"
      protons: True
      charge: -1
      toppar: False
      mol2: False



########################################################################
simulationInfo:
  - stepName: "01_energy_minimisation"
    type: "EM"
    temp: 300
    maxIterations: 1000

  - stepName: "02_NVT_pre-equilibraition"
    type: "NVT"
    duration: "100 ps"
    timestep: "2 fs"
    temp: 300
    restraints:
      - type: "position"
        selection: "protein"
      - type: "position"
        selection: "ligands"  
    logInterval: "10 ps"

  - stepName: "03_NpT_pre-equilibriation"
    type: "NpT"
    duration: "300 ps"
    timestep: "2 fs"
    temp: 300
    restraints:
      - type: "position"
        selection: "protein"
      - type: "position"
        selection: "ligands"
    logInterval: "10 ps"

  - stepName: "04_NpT_slowIntergrator"
    type: "NpT"
    duration: "10 ps"
    timestep: "0.5 fs"
    temp: 300
    logInterval: "1 ps"


  # - stepName: "05_NpT_design_restraints"
  #   type: "NpT"
  #   duration: "500 ps"
  #   timestep: "2 fs"
  #   temp: 400
  #   logInterval: "1 ps"
  #   restraints:
  #     - type: "distance"
  #       selection:
  #         - ["F","FE2","1","FE2"]
  #         - ["L","LIG","1","C71"]
  #       parameters:
  #         r0: 3
  #         k: 1000
  #     - type: "angle"
  #       selection:
  #         - ["C","WPC","1","ND"]
  #         - ["F","FE2","1","FE2"]
  #         - ["L","LIG","1","C71"]
  #       parameters:
  #         theta0: 90
  #         k: 300
  #     - type: "torsion"
  #       selection:
  #         - ["B","TPA","1","C8"]
  #         - ["B","TPA","1","O2"]
  #         - ["A","ARG","217","NH2"]
  #         - ["A","ARG","217","CZ"]
  #       parameters:
  #         theta0: 90
  #         k: 1000


  - stepName: "05_RMSD_Metadynamics_Dummy"
    type: "Meta"
    duration: "10 ps"
    timestep: "2 fs"
    temp: 400
    logInterval: "1 ps"
    metaDynamicsParams:
      height: 2
      biasFactor: 5
    biases: 
      - biasVar: "RMSD"
        selection: 
          type: "residue"
          input: 
          - ["A","FMN","248"]
    clusterTrajectory: 
      clusterBool: True
      nClusters: 10
      selection:
        type: "residue"
        input: 
        - ["A","FMN","248"]

    # restraints:
    #   - type: "position"
    #     selection: "protein"
        # type: "atom"
        # - ["B","GLN","6","O"]
        # - ["B","GLN","6","C"]
        # - ["B","GLN","6","CA"]
        # - ["B","GLN","6","CB"]
          # type: "backbone"
          # type: "protein"
          


  # # - stepName: "05_NpT_equilibriation"
  #   type: "NpT"
  #   duration: "1 ns"
  #   timestep: "2 fs"
  #   temp: 300

  # - stepName: "05_NpT_production_MD"
  #   type: "NpT"
  #   duration: "10 ns"
  #   timestep: "2 fs"
  #   freezeHeavy: False
  #   temp: 300

########################################################################
cleanUpInfo:
  getEndpointPdbs: True
  removeWaters : True
  removeIons : True
  keepFileNames: True