########################################################################
pathInfo:
  inputDir: "/home/esp/scriptDevelopment/drMD/01_inputs"
  outputDir: "/home/esp/scriptDevelopment/drMD/03_outputs"
  
########################################################################
generalInfo:
  parallelCPU: 1
  platform: "CUDA"
  subprocessCpus: 1

########################################################################
ligandInfo:
  nLigands: 1
  ligands:
    - ligandName: "FMN"
      protons: True
      charge: -1
      toppar: False
      mol2: False



########################################################################
simulationInfo:
  - stepName: "01_energy_minimisation"
    type: "EM"
    temp: 300
    maxIterations: 1000

  - stepName: "02_NVT_pre-equilibraition"
    type: "NVT"
    duration: "100 ps"
    timestep: "2 fs"
    temp: 300
    restraints:
    - type: "position"
      selection:
        type: "protein"
    - type: "position"
      selection: 
        type: "ligands"  
    logInterval: "10 ps"

  - stepName: "03_NpT_pre-equilibriation"
    type: "NpT"
    duration: "300 ps"
    timestep: "2 fs"
    temp: 300
    restraints:
    - type: "position"
      selection:
        type: "protein"
    - type: "position"
      selection: 
        type: "ligands"  
    logInterval: "10 ps"

  - stepName: "04_NpT_slowIntergrator"
    type: "NpT"
    duration: "10 ps"
    timestep: "0.5 fs"
    temp: 300
    logInterval: "1 ps"

  - stepName: "05_RMSD_Metadynamics_Dummy"
    type: "Meta"
    duration: "100 ps"
    timestep: "2 fs"
    temp: 400
    logInterval: "5 ps"
    metaDynamicsParams:
      height: 2
      biasFactor: 5
    biases: 
      - biasVar: "RMSD"
        selection: 
          type: "residue"
          input: 
          - ["A","FMN","248"]
    clusterTrajectory: 
      clusterBool: True
      nClusters: 10
      selection:
        type: "residue"
        input: 
        - ["A","FMN","248"]
    restraints:
    - type: "distance"
      selection:
        type: "atom"
        input:
        - ["A","FMN","248","P"]
        - ["A","FMN","248","C8M"]
      parameters:
        r0: 3
        k: 1000
    - type: "position"
      selection:
        type: "protein"
      parameters:
        k: 1000





  # - stepName: "05_NpT_equilibriation"
  #   type: "NpT"
  #   duration: "1 ns"
  #   timestep: "2 fs"
  #   temp: 300
  #   clusterTrajectory: 
  #     clusterBool: True
  #     nClusters: 10
  #     selection:
  #       type: "residue"
  #       input: 
  #       - ["A","FMN","248"]
  #   logInterval: "10 ps"
  # - stepName: "05_NpT_production_MD"
  #   type: "NpT"
  #   duration: "10 ns"
  #   timestep: "2 fs"
  #   freezeHeavy: False
  #   temp: 300

########################################################################
cleanUpInfo:
  getEndpointPdbs: True
  removeWaters : True
  removeIons : True
  keepFileNames: True