########################################################################
pathInfo:
  inputDir: "/home/esp/scriptDevelopment/drMD/01_inputs"
  outputDir: "/home/esp/scriptDevelopment/drMD/03_outputs"
  
########################################################################
generalInfo:
  parallelCPU: 1
  platform: "CUDA"
  subprocessCpus: 1

########################################################################
ligandInfo:
  nLigands: 1
  ligands:
    - ligandName: "FMN"
      protons: True
      charge: -1
      toppar: False
      mol2: False



########################################################################
simulationInfo:
  - stepName: "01_energy_minimisation"
    simulationType: "EM"
    temp: 300
    maxIterations: 1000
########################################################################
  - stepName: "02_NVT_pre-equilibraition"
    simulationType: "NVT"
    duration: "100 ps"
    timestep: "2 fs"
    temp: 300
    logInterval: "10 ps"
    restraintInfo:
    - restraintType: "position"
      parameters:
        k: 1000
      selection:
        keyword: "custom"
        customSelection:             
        - {CHAIN_ID: "A", RES_NAME: "all",RES_ID: [1,20], ATOM_NAME: "all"}

    - restraintType: "position"
      selection: 
        keyword: "ligands"  
      parameters:
        k: 1000
########################################################################
  - stepName: "03_NpT_pre-equilibriation"
    simulationType: "NpT"
    duration: "100 ps"
    timestep: "2 fs"
    temp: 300
    logInterval: "10 ps"
    restraintInfo:
    - restraintType: "position"
      selection:
        keyword: "protein"
      parameters: 
        k: 1000
    - restraintType: "position"
      selection: 
        keyword: "ligands"  
      parameters:
        k: 1000
########################################################################
  - stepName: "04_NpT_slowIntergrator"
    simulationType: "NpT"
    duration: "10 ps"
    timestep: "0.5 fs"
    temp: 300
    logInterval: "1 ps"
########################################################################
  - stepName: "05_RMSD_Metadynamics_Dummy"
    simulationType: "Meta"
    duration: "100 ps"
    timestep: "2 fs"
    temp: 400
    logInterval: "5 ps"
    metaDynamicsInfo:
      height: 2
      biasFactor: 5
      biases: 
        - biasVar: "RMSD"
          selection: 
            keyword: "custom"
            customSelection: 
            - {CHAIN_ID: "A", RES_NAME: "FMN",RES_ID: 248, ATOM_NAME: "all"}

    clusterTrajectory: 
      clusterBool: True
      nClusters: 10
      selection:
        keyword: "custom"
        customSelection: 
        - {CHAIN_ID: "A", RES_NAME: "FMN",RES_ID: 248, ATOM_NAME: "all"}

    restraintInfo:
    - restraintType: "distance"
      selection: 
        keyword: "custom"
        customSelection:
        - {CHAIN_ID: "A", RES_NAME: "FMN",RES_ID: 248, ATOM_NAME: "P"}
        - {CHAIN_ID: "A", RES_NAME: "FMN",RES_ID: 248, ATOM_NAME: "C8M"}
      parameters:
        r0: 3
        k: 1000
    - restraintType: "position"
      selection:
        keyword: "protein"
      parameters:
        k: 1000





  # - stepName: "05_NpT_equilibriation"
  #   simulationType: "NpT"
  #   duration: "1 ns"
  #   timestep: "2 fs"
  #   temp: 300
  #   clusterTrajectory: 
  #     clusterBool: True
  #     nClusters: 10
  #     selection:
  #       type: "residue"
  #       input: 
  #       - ["A","FMN","248"]
  #   logInterval: "10 ps"
  # - stepName: "05_NpT_production_MD"
  #   type: "NpT"
  #   duration: "10 ns"
  #   timestep: "2 fs"
  #   freezeHeavy: False
  #   temp: 300

########################################################################
cleanUpInfo:
  getEndpointPdbs: True
  removeWaters : True
  removeIons : True
  keepFileNames: True