pathInfo:
  inputDir: pwd
  outputDir: pwd

hardwareInfo:
  parallelCPU: 1
  platform: CPU
  subprocessCpus: 1

miscInfo:
  pH: 7
  firstAidMaxRetries: 10
  boxGeometry: cubic
  writeMyMethodsSection: True
  skipPdbTriage: False
  trajectorySelections:
  - selection:
      keyword: all
  