hardwareInfo:
  parallelCPU: 1
  platform: CUDA
  subprocessCpus: 1
ligandInfo:
- charge: -2
  ligandName: TPA
  mol2: false
  protons: false
  toppar: false
loggingInfo:
  trajectorySelections:
  - selection:
      keyword: protein
  - selection:
      keyword: ligand
miscInfo:
  boxGeometry: cubic
  firstAidMaxRetries: 10
  heavyProtons: true
  pH: 7.4
pathInfo:
  inputDir: /home/esp/scriptDevelopment/drMD/01_inputs
  inputPdb: /home/esp/scriptDevelopment/drMD/01_inputs/A0A0D2XFD3_TPA_1.pdb
  outputDir: /home/esp/scriptDevelopment/drMD/03_test_outputs/A0A0D2XFD3_TPA_1
  outputName: A0A0D2XFD3_TPA_1
proteinInfo:
  proteinName: A0A0D2XFD3_TPA_1
  protons: false
simulationInfo:
- maxIterations: 1000
  simulationType: EM
  stepName: 01_energy_minimisation
  temperature: 300
- duration: 100 ps
  heavyProtons: false
  logInterval: 10 ps
  restraintInfo: &id001
  - parameters:
      k: 1000
    restraintType: position
    selection:
      keyword: protein
  - parameters:
      k: 1000
    restraintType: position
    selection:
      keyword: ligand
  simulationType: NVT
  stepName: 02_NVT_pre-equilibraition
  temperature: 300
  timestep: 2 fs
- duration: 100 ps
  heavyProtons: true
  logInterval: 10 ps
  restraintInfo: *id001
  simulationType: NPT
  stepName: 03_NPT_pre-equilibraition
  temperature: 300
  timestep: 4 fs
- duration: 10 ps
  logInterval: 1 ps
  simulationType: NpT
  stepName: 04_NpT_slowIntergrator
  temperature: 300
  timestep: 0.5 fs
- duration: 5 ns
  heavyProtons: true
  logInterval: 50 ps
  simulationType: NpT
  stepName: 05_Production_MD
  temperature: 300
  timestep: 4 fs
