generalInfo:
  parallelCPU: 1
  platform: CUDA
  subprocessCpus: 1
pathInfo:
  inputDir: /home/esp/scriptDevelopment/drMD/01_inputs
  inputPdb: /home/esp/scriptDevelopment/drMD/01_inputs/A.pdb
  outputDir: /home/esp/scriptDevelopment/drMD/03_output/A
  outputName: A
proteinInfo:
  proteinName: A
  protons: false
simulationInfo:
- maxIterations: 1000
  restraintInfo:
  - parameters:
      k: 500
    restraintType: position
    selection:
      keyword: protein
  - parameters:
      k: 500
    restraintType: position
    selection:
      keyword: ligands
  simulationType: EM
  stepName: 011_energy_minimisation
  temperature: 0
- duration: 20 ps
  logInterval: 1 ps
  restraintInfo:
  - parameters:
      k: 150
    restraintType: position
    selection:
      keyword: ligands
  simulationType: NVT
  stepName: 021_NVT
  temperatureRange:
  - 10
  - 20
  - 30
  - 40
  - 50
  - 60
  - 70
  - 80
  - 100
  timestep: 2 fs
- duration: 9 ns
  logInterval: 100 ps
  restraintInfo:
  - parameters:
      k: 150
    restraintType: position
    selection:
      keyword: ligands
  simulationType: NPT
  stepName: 022_NpT
  temperatureRange:
  - 100
  - 125
  - 150
  - 175
  - 200
  - 225
  - 250
  - 275
  - 300
  timestep: 2 fs
