########################################################################
pathInfo:
  inputDir: "/scratch/deltaProteins/round2/RfDiffusionResults/round2/best_score"
  outputDir: "/scratch/deltaProteins/round2/RfDiffusionResults/round2/best_score_EM"
########################################################################
simulationInfo:
  - stepName: "01_energy_minimisation"
    type: "EM"
    temp: 300
    gpu: True
########################################################################
cleanUpInfo:
  pdbOnly: True