########################################################################
pathInfo:
  inputDir: "/home/esp/scriptDevelopment/drMD/01_inputs/omegafold_output"
  outputDir: "/home/esp/scriptDevelopment/drMD/03_outputs"
  
########################################################################
hardwareInfo:
  parallelCPU: 6
  platform: "CUDA"
  subprocessCpus: 1
########################################################################

simulationInfo:
  - stepName: "01_energy_minimisation"
    simulationType: "EM"
    temperature: 300
    maxIterations: 1000

################################################

postSimulationInfo:
  endPointInfo:
    stepNames: ["01_energy_minimisation"]
    removeAtoms: 
    - selection:
        keyword: "ions"
    - selection:
        keyword: "ligands"
    collate: True
  directoryCleanUpInfo:
    removeAllSimulationDirs: True
    # stepsToRemove: ["00_prep"]


