########################################################################
pathInfo:
  inputDir: "/home/esp/scriptDevelopment/drMD/01_inputs/"
  outputDir: "/home/esp/scriptDevelopment/drMD/03_outputs"
  
########################################################################
hardwareInfo:
  parallelCPU: 1
  platform: "CUDA"
  subprocessCpus: 1
########################################################################

simulationInfo:
  - stepName: "01_energy_minimisation"
    simulationType: "EM"
    temperature: 300
    maxIterations: 1000

  - stepName: "02_NVT_pre-equilibraition"
    simulationType: "NVT"
    duration: "50 ps"
    timestep: "2 fs"
    temperature: 300
    logInterval: "5 ps"
    restraintInfo:
    - restraintType: "position"
      parameters:
        k: 1000 
      selection:
        keyword: "protein"
    - restraintType: "position"
      selection: 
        keyword: "ligands"  
      parameters:
        k: 1000
################################################



