########################################################################
pathInfo:
  inputDir: /home/esp/scriptDevelopment/drMD/01_inputs/test_standard
  outputDir: "/home/esp/scriptDevelopment/drMD/03_metadynamics_outputs"
  
########################################################################
hardwareInfo:
  parallelCPU: 1
  platform: "CUDA"
  subprocessCpus: 1
########################################################################
miscInfo:
  pH: 7.4
  firstAidMaxRetries: 10
  boxGeometry: "cubic"
  writeMyMethodsSection: True
  skipPdbTriage: False
  trajectorySelections:
  - selection:
      keyword: "protein"
  - selection:
      keyword: "ligand"

########################################################################
equilibriationRestraints: &equilibriationRestraints
    - restraintType: "position"
      parameters:
        k: 1000
      selection:
        keyword: "protein"

    - restraintType: "position"
      selection: 
        keyword: "ligand"  
      parameters:
        k: 1000

########################################################################
simulationInfo:
  - stepName: "01_energy_minimisation"
    simulationType: "EM"
    temperature: 300
    maxIterations: -1
########################################################################
  - stepName: "02_NVT_pre-equilibraition"
    simulationType: "NVT"
    duration: "100 ps"
    timestep: "4 fs"
    heavyProtons: True
    temperature: 300
    logInterval: "10 ps"
    restraintInfo: *equilibriationRestraints

# ########################################################################
  - stepName: "03_NPT_pre-equilibraition"
    simulationType: "NPT"
    duration: "100 ps"
    timestep: "4 fs"
    heavyProtons: True
    temperature: 300
    logInterval: "10 ps"
    restraintInfo: *equilibriationRestraints

########################################################################
  - stepName: "04_NpT_slowIntergrator"
    simulationType: "NpT"
    duration: "10 ps"
    timestep: "0.5 fs"
    temperature: 300
    logInterval: "1 ps"
########################################################################
  - stepName: "05_Metadynamics"
    simulationType: "META"
    duration: "5 ns"
    timestep: "4 fs"
    heavyProtons: True
    temperature: 300
    logInterval: "50 ps"
    metaDynamicsInfo:
      height: 2
      biasFactor: 5
      frequency: 50
      biases:
      - biasVar: "rmsd"
        minValue: 0
        maxValue: dog
        biasWidth: 1
        selection:
          keyword: "backbone"
################################################
postSimulationInfo:
  clusterInfo:
    stepNames: ["05_Metadynamics"] 
    nClusters: 25
    clusterBy:
    - selection:
        keyword: "protein"
    removeAtoms:
      - selection:
          keyword: "water"
      - selection:
          keyword: "ions"


