########################################################################
pathInfo:
  inputDir: /home/esp/scriptDevelopment/drMD/01_inputs/PET_proj
  outputDir: /home/esp/scriptDevelopment/drAnalysis/PETase_MD_for_drMD_paper/04_PET_proj_outputs
  
########################################################################
miscInfo:
  pH: 7.4
  firstAidMaxRetries: 10
  boxGeometry: octahedral
  skipPdbTriage: False
  firstAidMaxRetries: 0
  writeMyMethodsSection: True
  trajectorySelections:
  - selection:
      keyword: protein
  - selection:
      keyword: ligand
########################################################################
hardwareInfo:
  parallelCPU: 1
  platform: CUDA
  subprocessCpus: 1
########################################################################
simulationInfo:
## EM STEPS ##################################
  - stepName: 011_energy_minimisation
    simulationType: EM
    temperature: 300
    maxIterations: -1
    restraintInfo:
    - restraintType: position
      parameters:
        k: 500
      selection:
        keyword: all

  ##
  - stepName: 012_energy_minimisation
    simulationType: EM
    temperature: 300
    maxIterations: -1
    restraintInfo:
    - restraintType: position
      parameters:
        k: 430
      selection:
        keyword: all

  ##
  - stepName: 013_energy_minimisation
    simulationType: EM
    temperature: 300
    maxIterations: -1
    restraintInfo:
    - restraintType: position
      parameters:
        k: 360
      selection:
        keyword: all

  ##
  - stepName: 014_energy_minimisation
    simulationType: EM
    temperature: 300
    maxIterations: -1
    restraintInfo:
    - restraintType: position
      parameters:
        k: 290
      selection:
        keyword: all

  ##
  - stepName: 015_energy_minimisation
    simulationType: EM
    temperature: 300
    maxIterations: -1
    restraintInfo:
    - restraintType: position
      parameters:
        k: 220
      selection:
        keyword: all

  ##
  - stepName: 015_energy_minimisation
    simulationType: EM
    temperature: 300
    maxIterations: -1
    restraintInfo:
    - restraintType: position
      parameters:
        k: 150
      selection:
        keyword: all

  ##
  - stepName: 016_energy_minimisation
    simulationType: EM
    temperature: 300
    maxIterations: -1
    restraintInfo:
    - restraintType: position
      parameters:
        k: 80
      selection:
        keyword: all

  ##
  - stepName: 017_energy_minimisation
    simulationType: EM
    temperature: 300
    maxIterations: -1
## EQUILIBRATION STEPS #######################
  - stepName: 021_NVT_warmup
    simulationType: NVT
    duration: 20 ps
    heavyProtons: true
    timestep: 4 fs
    temperatureRange: [10,20,30,40,50,60,70,80,100]
    logInterval: 1 ps
    restraintInfo:
    - restraintType: position
      parameters:
        k: 150
      selection:
        keyword: ligand
  ##
  - stepName: 022_NpT_warmup
    simulationType: NPT
    duration: 9 ns
    heavyProtons: true
    timestep: 4 fs
    temperatureRange: [100, 125, 150, 175, 200, 225, 250, 275, 300]
    logInterval: 100 ps
    restraintInfo:
    - restraintType: position
      parameters:
        k: 150
      selection:
        keyword: ligand

  ##
  - stepName: 023_NpT_equilibration
    simulationType: NPT
    duration: 5 ns
    heavyProtons: true
    timestep: 4 fs
    temperature: 300
    logInterval: 100 ps
    restraintInfo:
    - restraintType: position
      parameters:
        k: 150
      selection:
        keyword: ligand
## PRODUCTION MD #######################
  - stepName: 031_production_md
    simulationType: NPT
    duration: 500 ns
    heavyProtons: true
    timestep: 4 fs
    temperature: 300
    logInterval: 10 ps

