########################################################################
pathInfo:
  inputDir: /home/esp/scriptDevelopment/drMD/01_inputs/test_em
  outputDir: /home/esp/scriptDevelopment/drMD/03_short_outputs
  
########################################################################
hardwareInfo:
  parallelCPU: 8
  platform: CUDA
  subprocessCpus: 1

########################################################################
miscInfo:
  pH: 7.4
  boxGeometry: cubic
  trajectorySelections:
  - selection:
      keyword: protein
  - selection:  
      keyword: ligand

########################################################################

equilibriationRestraints: &equilibriationRestraints
    - restraintType: "position"
      parameters:
        k: 1000
      selection:
        keyword: "protein"

    - restraintType: "position"
      selection: 
        keyword: "ligand"  
      parameters:
        k: 1000

########################################################################
simulationInfo:
  - stepName: "01_energy_minimisation"
    simulationType: "EM"
    temperature: 300
    maxIterations: -1
####
  - stepName: "02_NVT_pre-equilibraition"
    simulationType: "NVT"
    duration: "100 ps"
    timestep: "4 fs"
    heavyProtons: True
    temperature: 300
    logInterval: "10 ps"
    restraintInfo: *equilibriationRestraints


postSimulationInfo:
  collateVitalsReports: True
